In [5]:
from pyspark.sql import SparkSession

spark = (
    SparkSession.builder
    .remote(
        "sc://localhost:15002/"
        ";user_id=Khushi"
        ";session_id=550e8400-e29b-41d4-a716-446655440001"
        ";user_agent=my-jupyter-client"
    )
    .appName("My Analytics Session")
    .getOrCreate()
)

In [15]:
spark.conf.get("spark.app.name")  # Returns "My Analytics Session"
# spark.conf.get("spark.app.user")  # Returns "My Analytics Session"
spark.conf.getAll

{'spark.eventLog.enabled': 'true',
 'spark.driver.port': '37875',
 'spark.sql.catalog.spark_catalog': 'org.apache.spark.sql.delta.catalog.DeltaCatalog',
 'spark.app.name': 'My Analytics Session',
 'spark.hadoop.fs.s3a.vectored.read.max.merged.size': '2M',
 'spark.app.initial.file.urls': 'spark://spark-master:37875/files/com.google.code.findbugs_jsr305-3.0.2.jar,spark://spark-master:37875/files/org.apache.logging.log4j_log4j-api-2.25.3.jar,spark://spark-master:37875/files/org.apache.sedona_sedona-spark-shaded-4.1_2.13-1.9.0.jar,spark://spark-master:37875/files/org.lz4_lz4-java-1.8.0.jar,spark://spark-master:37875/files/org.xerial.snappy_snappy-java-1.1.10.8.jar,spark://spark-master:37875/files/org.tukaani_xz-1.10.jar,spark://spark-master:37875/files/io.unitycatalog_unitycatalog-client-0.4.0.jar,spark://spark-master:37875/files/org.scala-lang.modules_scala-parallel-collections_2.13-1.2.0.jar,spark://spark-master:37875/files/org.apache.commons_commons-pool2-2.12.1.jar,spark://spark-master:37875/files/org.apache.kafka_kafka-clients-3.9.1.jar,spark://spark-master:37875/files/org.apache.logging.log4j_log4j-core-2.25.3.jar,spark://spark-master:37875/files/org.apache.spark_spark-avro_2.13-4.1.2.jar,spark://spark-master:37875/files/org.apache.hadoop_hadoop-client-api-3.4.2.jar,spark://spark-master:37875/files/io.delta_delta-spark_4.1_2.13-4.1.0.jar,spark://spark-master:37875/files/org.apache.hadoop_hadoop-client-runtime-3.4.2.jar,spark://spark-master:37875/files/org.apache.spark_spark-token-provider-kafka-0-10_2.13-4.1.2.jar,spark://spark-master:37875/files/org.checkerframework_checker-qual-3.42.0.jar,spark://spark-master:37875/files/org.apache.spark_spark-sql-kafka-0-10_2.13-4.1.2.jar,spark://spark-master:37875/files/org.postgresql_postgresql-42.7.3.jar,spark://spark-master:37875/files/org.apache.logging.log4j_log4j-slf4j2-impl-2.25.3.jar,spark://spark-master:37875/files/org.slf4j_slf4j-api-2.0.13.jar,spark://spark-master:37875/files/io.delta_delta-storage-4.1.0.jar',
 'spark.submit.deployMode': 'client',
 'spark.master': 'spark://spark-master:7077',
 'spark.hadoop.javax.jdo.option.ConnectionURL': 'jdbc:derby:/opt/spark/metastore/metastore_db;create=true',
 'spark.eventLog.dir': 'file:/opt/spark/event_logs',
 'spark.sql.catalogImplementation': 'hive',
 'spark.repl.local.jars': 'file:///tmp/.ivy/jars/io.delta_delta-spark_4.1_2.13-4.1.0.jar,file:///tmp/.ivy/jars/org.apache.spark_spark-sql-kafka-0-10_2.13-4.1.2.jar,file:///tmp/.ivy/jars/org.apache.spark_spark-avro_2.13-4.1.2.jar,file:///tmp/.ivy/jars/org.apache.sedona_sedona-spark-shaded-4.1_2.13-1.9.0.jar,file:///tmp/.ivy/jars/org.postgresql_postgresql-42.7.3.jar,file:///tmp/.ivy/jars/io.delta_delta-storage-4.1.0.jar,file:///tmp/.ivy/jars/io.unitycatalog_unitycatalog-client-0.4.0.jar,file:///tmp/.ivy/jars/org.slf4j_slf4j-api-2.0.13.jar,file:///tmp/.ivy/jars/org.apache.logging.log4j_log4j-slf4j2-impl-2.25.3.jar,file:///tmp/.ivy/jars/org.apache.logging.log4j_log4j-api-2.25.3.jar,file:///tmp/.ivy/jars/com.google.code.findbugs_jsr305-3.0.2.jar,file:///tmp/.ivy/jars/org.apache.logging.log4j_log4j-core-2.25.3.jar,file:///tmp/.ivy/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.13-4.1.2.jar,file:///tmp/.ivy/jars/org.scala-lang.modules_scala-parallel-collections_2.13-1.2.0.jar,file:///tmp/.ivy/jars/org.apache.kafka_kafka-clients-3.9.1.jar,file:///tmp/.ivy/jars/org.apache.commons_commons-pool2-2.12.1.jar,file:///tmp/.ivy/jars/org.apache.hadoop_hadoop-client-runtime-3.4.2.jar,file:///tmp/.ivy/jars/org.lz4_lz4-java-1.8.0.jar,file:///tmp/.ivy/jars/org.xerial.snappy_snappy-java-1.1.10.8.jar,file:///tmp/.ivy/jars/org.apache.hadoop_hadoop-client-api-3.4.2.jar,file:///tmp/.ivy/jars/org.tukaani_xz-1.10.jar,file:///tmp/.ivy/jars/org.checkerframework_checker-qual-3.42.0.jar',
 'spark.sql.extensions': 'org.apache.sedona.sql.SedonaSqlExtensions,io.delta.sql.DeltaSparkSessionExtension',
 'spark.app.id': 'app-20260906064013-0000',
 'spark.jars.ivy': '/tmp/.ivy',
 'spark.sql.warehouse.dir': 'file:/opt/spark/warehouse',
 'spark.executor.extraJavaOptions': '-Djava.net.preferIPv6Addresses=false -XX:+IgnoreUnrecognizedVMOptions --add-modules=jdk.incubator.vector --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED --add-opens=java.base/jdk.internal.ref=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/sun.nio.cs=ALL-UNNAMED --add-opens=java.base/sun.security.action=ALL-UNNAMED --add-opens=java.base/sun.util.calendar=ALL-UNNAMED --add-opens=java.security.jgss/sun.security.krb5=ALL-UNNAMED -Djdk.reflect.useDirectMethodHandle=false -Dio.netty.tryReflectionSetAccessible=true -Dio.netty.allocator.type=pooled -Dio.netty.handler.ssl.defaultEndpointVerificationAlgorithm=NONE --enable-native-access=ALL-UNNAMED',
 'spark.driver.host': 'spark-master',
 'spark.hadoop.fs.s3a.vectored.read.min.seek.size': '128K',
 'spark.jars': 'file:///tmp/.ivy/jars/io.delta_delta-spark_4.1_2.13-4.1.0.jar,file:///tmp/.ivy/jars/org.apache.spark_spark-sql-kafka-0-10_2.13-4.1.2.jar,file:///tmp/.ivy/jars/org.apache.spark_spark-avro_2.13-4.1.2.jar,file:///tmp/.ivy/jars/org.apache.sedona_sedona-spark-shaded-4.1_2.13-1.9.0.jar,file:///tmp/.ivy/jars/org.postgresql_postgresql-42.7.3.jar,file:///tmp/.ivy/jars/io.delta_delta-storage-4.1.0.jar,file:///tmp/.ivy/jars/io.unitycatalog_unitycatalog-client-0.4.0.jar,file:///tmp/.ivy/jars/org.slf4j_slf4j-api-2.0.13.jar,file:///tmp/.ivy/jars/org.apache.logging.log4j_log4j-slf4j2-impl-2.25.3.jar,file:///tmp/.ivy/jars/org.apache.logging.log4j_log4j-api-2.25.3.jar,file:///tmp/.ivy/jars/com.google.code.findbugs_jsr305-3.0.2.jar,file:///tmp/.ivy/jars/org.apache.logging.log4j_log4j-core-2.25.3.jar,file:///tmp/.ivy/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.13-4.1.2.jar,file:///tmp/.ivy/jars/org.scala-lang.modules_scala-parallel-collections_2.13-1.2.0.jar,file:///tmp/.ivy/jars/org.apache.kafka_kafka-clients-3.9.1.jar,file:///tmp/.ivy/jars/org.apache.commons_commons-pool2-2.12.1.jar,file:///tmp/.ivy/jars/org.apache.hadoop_hadoop-client-runtime-3.4.2.jar,file:///tmp/.ivy/jars/org.lz4_lz4-java-1.8.0.jar,file:///tmp/.ivy/jars/org.xerial.snappy_snappy-java-1.1.10.8.jar,file:///tmp/.ivy/jars/org.apache.hadoop_hadoop-client-api-3.4.2.jar,file:///tmp/.ivy/jars/org.tukaani_xz-1.10.jar,file:///tmp/.ivy/jars/org.checkerframework_checker-qual-3.42.0.jar',
 'spark.sql.artifact.isolation.enabled': 'true',
 'spark.hadoop.javax.jdo.option.ConnectionDriverName': 'org.apache.derby.jdbc.EmbeddedDriver',
 'spark.submit.pyFiles': '/tmp/.ivy/jars/io.delta_delta-spark_4.1_2.13-4.1.0.jar,/tmp/.ivy/jars/org.apache.spark_spark-sql-kafka-0-10_2.13-4.1.2.jar,/tmp/.ivy/jars/org.apache.spark_spark-avro_2.13-4.1.2.jar,/tmp/.ivy/jars/org.apache.sedona_sedona-spark-shaded-4.1_2.13-1.9.0.jar,/tmp/.ivy/jars/org.postgresql_postgresql-42.7.3.jar,/tmp/.ivy/jars/io.delta_delta-storage-4.1.0.jar,/tmp/.ivy/jars/io.unitycatalog_unitycatalog-client-0.4.0.jar,/tmp/.ivy/jars/org.slf4j_slf4j-api-2.0.13.jar,/tmp/.ivy/jars/org.apache.logging.log4j_log4j-slf4j2-impl-2.25.3.jar,/tmp/.ivy/jars/org.apache.logging.log4j_log4j-api-2.25.3.jar,/tmp/.ivy/jars/com.google.code.findbugs_jsr305-3.0.2.jar,/tmp/.ivy/jars/org.apache.logging.log4j_log4j-core-2.25.3.jar,/tmp/.ivy/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.13-4.1.2.jar,/tmp/.ivy/jars/org.scala-lang.modules_scala-parallel-collections_2.13-1.2.0.jar,/tmp/.ivy/jars/org.apache.kafka_kafka-clients-3.9.1.jar,/tmp/.ivy/jars/org.apache.commons_commons-pool2-2.12.1.jar,/tmp/.ivy/jars/org.apache.hadoop_hadoop-client-runtime-3.4.2.jar,/tmp/.ivy/jars/org.lz4_lz4-java-1.8.0.jar,/tmp/.ivy/jars/org.xerial.snappy_snappy-java-1.1.10.8.jar,/tmp/.ivy/jars/org.apache.hadoop_hadoop-client-api-3.4.2.jar,/tmp/.ivy/jars/org.tukaani_xz-1.10.jar,/tmp/.ivy/jars/org.checkerframework_checker-qual-3.42.0.jar',
 'spark.app.submitTime': '1788676810956',
 'spark.jars.packages': 'io.delta:delta-spark_4.1_2.13:4.1.0,org.apache.spark:spark-sql-kafka-0-10_2.13:4.1.2,org.apache.spark:spark-avro_2.13:4.1.2,org.apache.sedona:sedona-spark-shaded-4.1_2.13:1.9.0,org.postgresql:postgresql:42.7.3',
 'spark.sql.artifact.isolation.alwaysApplyClassloader': 'true',
 'spark.files': 'file:///tmp/.ivy/jars/io.delta_delta-spark_4.1_2.13-4.1.0.jar,file:///tmp/.ivy/jars/org.apache.spark_spark-sql-kafka-0-10_2.13-4.1.2.jar,file:///tmp/.ivy/jars/org.apache.spark_spark-avro_2.13-4.1.2.jar,file:///tmp/.ivy/jars/org.apache.sedona_sedona-spark-shaded-4.1_2.13-1.9.0.jar,file:///tmp/.ivy/jars/org.postgresql_postgresql-42.7.3.jar,file:///tmp/.ivy/jars/io.delta_delta-storage-4.1.0.jar,file:///tmp/.ivy/jars/io.unitycatalog_unitycatalog-client-0.4.0.jar,file:///tmp/.ivy/jars/org.slf4j_slf4j-api-2.0.13.jar,file:///tmp/.ivy/jars/org.apache.logging.log4j_log4j-slf4j2-impl-2.25.3.jar,file:///tmp/.ivy/jars/org.apache.logging.log4j_log4j-api-2.25.3.jar,file:///tmp/.ivy/jars/com.google.code.findbugs_jsr305-3.0.2.jar,file:///tmp/.ivy/jars/org.apache.logging.log4j_log4j-core-2.25.3.jar,file:///tmp/.ivy/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.13-4.1.2.jar,file:///tmp/.ivy/jars/org.scala-lang.modules_scala-parallel-collections_2.13-1.2.0.jar,file:///tmp/.ivy/jars/org.apache.kafka_kafka-clients-3.9.1.jar,file:///tmp/.ivy/jars/org.apache.commons_commons-pool2-2.12.1.jar,file:///tmp/.ivy/jars/org.apache.hadoop_hadoop-client-runtime-3.4.2.jar,file:///tmp/.ivy/jars/org.lz4_lz4-java-1.8.0.jar,file:///tmp/.ivy/jars/org.xerial.snappy_snappy-java-1.1.10.8.jar,file:///tmp/.ivy/jars/org.apache.hadoop_hadoop-client-api-3.4.2.jar,file:///tmp/.ivy/jars/org.tukaani_xz-1.10.jar,file:///tmp/.ivy/jars/org.checkerframework_checker-qual-3.42.0.jar',
 'spark.app.startTime': '1788676811759',
 'spark.executor.id': 'driver',
 'spark.driver.extraJavaOptions': '-Djava.net.preferIPv6Addresses=false -XX:+IgnoreUnrecognizedVMOptions --add-modules=jdk.incubator.vector --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED --add-opens=java.base/jdk.internal.ref=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/sun.nio.cs=ALL-UNNAMED --add-opens=java.base/sun.security.action=ALL-UNNAMED --add-opens=java.base/sun.util.calendar=ALL-UNNAMED --add-opens=java.security.jgss/sun.security.krb5=ALL-UNNAMED -Djdk.reflect.useDirectMethodHandle=false -Dio.netty.tryReflectionSetAccessible=true -Dio.netty.allocator.type=pooled -Dio.netty.handler.ssl.defaultEndpointVerificationAlgorithm=NONE --enable-native-access=ALL-UNNAMED',
 'spark.app.initial.jar.urls': 'spark://spark-master:37875/jars/org.apache.logging.log4j_log4j-slf4j2-impl-2.25.3.jar,spark://spark-master:37875/jars/org.apache.commons_commons-pool2-2.12.1.jar,spark://spark-master:37875/jars/com.google.code.findbugs_jsr305-3.0.2.jar,spark://spark-master:37875/jars/org.apache.spark_spark-sql-kafka-0-10_2.13-4.1.2.jar,spark://spark-master:37875/jars/io.delta_delta-spark_4.1_2.13-4.1.0.jar,spark://spark-master:37875/jars/org.slf4j_slf4j-api-2.0.13.jar,spark://spark-master:37875/jars/org.apache.logging.log4j_log4j-api-2.25.3.jar,spark://spark-master:37875/jars/org.apache.spark_spark-token-provider-kafka-0-10_2.13-4.1.2.jar,spark://spark-master:37875/jars/org.apache.hadoop_hadoop-client-api-3.4.2.jar,spark://spark-master:37875/jars/org.apache.sedona_sedona-spark-shaded-4.1_2.13-1.9.0.jar,spark://spark-master:37875/jars/org.lz4_lz4-java-1.8.0.jar,spark://spark-master:37875/jars/io.delta_delta-storage-4.1.0.jar,spark://spark-master:37875/jars/org.postgresql_postgresql-42.7.3.jar,spark://spark-master:37875/jars/org.xerial.snappy_snappy-java-1.1.10.8.jar,spark://spark-master:37875/jars/org.scala-lang.modules_scala-parallel-collections_2.13-1.2.0.jar,spark://spark-master:37875/jars/org.tukaani_xz-1.10.jar,spark://spark-master:37875/jars/io.unitycatalog_unitycatalog-client-0.4.0.jar,spark://spark-master:37875/jars/org.apache.spark_spark-avro_2.13-4.1.2.jar,spark://spark-master:37875/jars/org.checkerframework_checker-qual-3.42.0.jar,spark://spark-master:37875/jars/org.apache.kafka_kafka-clients-3.9.1.jar,spark://spark-master:37875/jars/org.apache.hadoop_hadoop-client-runtime-3.4.2.jar,spark://spark-master:37875/jars/org.apache.logging.log4j_log4j-core-2.25.3.jar'}

In [ ]:
spark.stop()

In [17]:
from pyspark.sql import SparkSession

spark = (
    SparkSession.builder
    .remote(
        "sc://localhost:15002/;user_id=ervijay"
    )
    .appName("My Analytics Session")
    .config("my.session.project", "customer-analytics")
    .config("my.session.environment", "production")
    .config("my.session.owner", "ervijay")
    .getOrCreate()
)

In [19]:
spark.conf.get("my.session.project")

'customer-analytics'

In [20]:
from pyspark.sql import functions as F

df = (
    spark.range(1_000_000)
    .withColumn("value", F.rand(seed=42))
    .withColumn(
        "category",
        F.when(F.col("value") < 0.25, "A")
         .when(F.col("value") < 0.50, "B")
         .when(F.col("value") < 0.75, "C")
         .otherwise("D")
    )
)

df.createOrReplaceTempView("test_large_result")

In [21]:
spark.sql("""
    SELECT *
    FROM test_large_result
    LIMIT 10
""").show()

+---+-------------------+--------+
| id|              value|category|
+---+-------------------+--------+
|  0|  0.619189370225301|       C|
|  1| 0.5096018842446481|       C|
|  2| 0.8325259388871524|       D|
|  3|0.26322809041172357|       B|
|  4| 0.6702867696264135|       C|
|  5| 0.5173283545794627|       C|
|  6| 0.9991441647585968|       D|
|  7|0.06993233728279169|       A|
|  8| 0.9696695610826327|       D|
|  9| 0.7959575617927873|       D|
+---+-------------------+--------+

In [22]:
spark.sql("SELECT COUNT(*) FROM test_large_result").show()

+--------+
|count(1)|
+--------+
| 1000000|
+--------+

In [23]:
page_size = 1000

page = (
    spark.table("test_large_result")
    .orderBy("id")
    .limit(page_size)
)

pdf = page.toPandas()

pdf.head()

   id     value category
0   0  0.619189        C
1   1  0.509602        C
2   2  0.832526        D
3   3  0.263228        B
4   4  0.670287        C

In [32]:
page = (
    spark.table("test_large_result")
    .orderBy("id")
    .offset(1000001)
    .limit(1000)
)

pdf = page.toPandas()

pdf.head()

Empty DataFrame
Columns: [id, value, category]
Index: []

In [25]:
page = (
    spark.table("test_large_result")
    .orderBy("id")
    .offset(2000)
    .limit(1000)
)

pdf = page.toPandas()

In [1]:
from pyspark.sql import SparkSession


spark1 = (
    SparkSession.builder
    .remote("sc://localhost:15002")
    .getOrCreate()
)

print("session:", spark1.session_id)
print("app:", spark1.conf.get("spark.app.id"))

session: e770e0e7-22f4-4a1e-aac9-fc20fc6a6c04
app: app-20260906064013-0000

In [2]:
spark1.sql("""
    CREATE OR REPLACE TEMP VIEW session_a_view AS
    SELECT 1 AS value
""")

DataFrame[]

### Application name and ID

In [19]:

from pyspark.sql import SparkSession

spark = (
    SparkSession.builder
    .remote("sc://localhost:15002")
    .appName("livy-session-42")
    .getOrCreate()
)

In [2]:
spark.conf.get("spark.app.name")

'livy-session-42'

In [14]:
spark = (
    SparkSession.builder
    .remote("sc://localhost:15002")
    .config("spark.livy.session.id", "42")
    .config("spark.livy.user", "Khushi")
    .config("spark.livy.session.type", "interactive")
    .getOrCreate()
)

In [6]:
import pyspark

pyspark.__version__

# print("App ID:", spark.conf.get("spark.app.id"))
# print("UI enabled:", spark.conf.get("spark.ui.enabled"))
# print("UI port:", spark.conf.get("spark.ui.port"))

'4.2.0'

In [30]:
from pyspark.sql import SparkSession

spark = SparkSession.builder.remote(
    "sc://localhost:15002"
).getOrCreate()

In [2]:
print("Application ID:", spark.conf.get("spark.app.id"))
print("App Name:", spark.conf.get("spark.app.name"))
print("Session ID:", spark.session_id)

Application ID: app-20260906064013-0000
App Name: livy-next
Session ID: 7eaf3b92-a606-46ef-875c-afe211ea0881

In [20]:
spark.stop()

In [17]:
print("Application ID:", spark.conf.get("spark.app.id"))
print("App Name:", spark.conf.get("spark.app.name"))
print("Session ID:", spark.session_id)

Application ID: app-20260906064013-0000
App Name: livy-next
Session ID: 29c9840c-e752-4cf3-b67a-fe23f29336c1

In [4]:
print(spark)

<pyspark.sql.connect.session.SparkSession object at 0x115f83a10>

In [3]:
df = spark1.range(3, 31, 1)
df.show()

+---+
| id|
+---+
|  3|
|  4|
|  5|
|  6|
|  7|
|  8|
|  9|
| 10|
| 11|
| 12|
| 13|
| 14|
| 15|
| 16|
| 17|
| 18|
| 19|
| 20|
| 21|
| 22|
+---+
only showing top 20 rows

In [9]:
spark.session_id

'82b0a542-1a6e-4f70-baaf-54de08838384'

In [ ]:
spark.conf.get("spark.app.id")
# 'app-20260906064013-0000'

'app-20260906064013-0000'